TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 1
  EVAL_PERIOD: 15
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: False
  # CHECKPOINT_FILE_PATH: path to the pretrain checkpoint file.
  CHECKPOINT_TYPE: pytorch
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: True
AVA:
  FRAME_DIR: ../PSI-AVA_code/PSI-AVA/data/ 
  FRAME_LIST_DIR: ../PSI-AVA_code/PSI-AVA/frame_lists/Split_7/
  ANNOTATION_DIR: ../PSI-AVA_code/PSI-AVA/annotations_ava/Split_7/ 
  TRAIN_LISTS: ['train.csv']
  TEST_LISTS: ['val.csv']
  TRAIN_GT_BOX_LISTS: ['train.csv']
  TRAIN_PREDICT_BOX_LISTS: ['train_predict.csv']
  TEST_PREDICT_BOX_LISTS: ['val.csv']
  DETECTION_SCORE_THRESH: 0.8
  BGR: False
  TRAIN_USE_COLOR_AUGMENTATION: False 
  TRAIN_PCA_JITTER_ONLY: True
  TEST_FORCE_FLIP: False 
  FULL_TEST_ON_VAL: False       
  LABEL_MAP_FILE: action_list.pbtxt 
  EXCLUSION_FILE: exclud.csv
  GROUNDTRUTH_FILE: val.csv 
  IMG_PROC_BACKEND: cv2
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 15, 20]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 16
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 1
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 0
RNG_SEED: 0
OUTPUT_DIR: Split_7_slowfast/
